fix: increase NODE memory to avoid OOM during docker frontend build
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Likely because we added more frontend component which overloads the memory during build.

Solution found from https://stackoverflow.com/questions/62663167/dockerizing-react-in-production-mode-fatal-error-ineffective-mark-compacts-nea

Needs to increase the docker memory setting as well to make thie effective