fix: increase NODE memory to avoid OOM during docker frontend build (#334)
* chore: pre-release v0.11.0

bump up version

* fix: increase NODE memory to avoid OOM during docker frontend build

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Likely because we added more frontend component which overloads the memory during build.

Solution found from https://stackoverflow.com/questions/62663167/dockerizing-react-in-production-mode-fatal-error-ineffective-mark-compacts-nea

Needs to increase the docker memory setting as well to make thie effective

Co-authored-by: Yunwei Xiao <xiaoluoboding@gmail.com>
Former-commit-id: d770cd9960c6e56d67950e8ea0f28600e1fff7a9 [formerly 4728dee283f652e678f83d5057805efe0b7d33d3]
Former-commit-id: 52815e3d1c4d23c9f74983c5c81dcc1d9ec98ec9